### ISSUE TITLE
Constant accelerations while stationary

### ISSUE THREAD

**Issue by NCharabaruk** [ros-drivers/um7#2]
Hello,

I was checking out the data from package and I found that I am getting constant linear accelerations in the y and x directions despite the fact that the IMU is stationary. They are in the range of 0.12-0.17. Any ideas on why this may be?

Nick

**Comment by rbirac** [comment]
Hi Nick,

```
The X and Y axes pick up part of the gravity vector unless the accelerometers are mounted perfectly level.  Also, the accelerations may vary somewhat due to tolerances.  Since both X and Y vary to the sine of angular error to true vertical, and gravity being 9.8 M/sec/sec, the values you are seeing indicate angular errors of one degree or less.   Since the UM7 calculates and corrects the Z axis angle to the X and Y accel values, these offsets will cause errors in pitch and roll axes of about one degree.  For most purposes, this is pretty good.
```

   On my robot,  I shimmed the UM7 installation to minimize the X and Y accels when the robot is on a level floor.  It is also desirable to have the X axis carefully aligned with the robot’s forward direction so that forward accel by the robot doesn’t affect the Y axis and vice versa.  

Alex

Alex

From: Nick Charabaruk 
Sent: Thursday, June 04, 2015 8:12 AM
To: ros-drivers/um7 
Subject: [um7] Constant accelerations while stationary (#2)

Hello,

I was checking out the data from package and I found that I am getting constant linear accelerations in the y and x directions despite the fact that the IMU is stationary. They are in the range of 0.12-0.17. Any ideas on why this may be?

Nick

**Comment by NCharabaruk** [comment]
I did not think of that. Thanks for your time.
